language: python
python: 
  - "2.7"
cache: pip
install: pip install pyflakes
script:
  - pyflakes *.py
  - python -c 'print "Finished static analysis"'
notifications:
  email:
    - brian@bioconductor.org
